### ISSUE TITLE
Issues with new autolathe recipes

### ISSUE THREAD

**Issue by ourpar** [Persistent-SS13/Persistent-Bay#233] opened 2018-05-25 21:33 UTC
#### Description of issue
1. Some recipes in the autolathe call for "metal" to be used when printing items. These should be changed to "steel" since that is the proper material used.

2. (Possibly not a bug) Some items require "waste" and it's not possible to print items without this "waste" material, either there needs to be a better term to describe what the "waste" material is, or it should be removed from the materials list.

3. Material items still have the option to print multiple items like how they were before the new autolathe update. [This is probably better explained with a picture.](https://i.imgur.com/OsH3GG2.png)

4. Upgraded autolathes can print materials at a reduced price (example: 1x steel at 1600 materials), however, putting the 1x steel back in the autolathe will add 2000 material to the storage, essentially unlimited duping bug.

#### Length of time in which bug has been known to occur
Since the new autolathe update.

#### Client version, Server revision & Game ID
Client Version: 511
Server Revision: 5f88f7ba7839383c3cd849182fece2683ae5ff29 - dev - 2018-05-25
Game ID: bUx-dazv

**Comment by PrPleGoo** [comment] 2018-05-25 21:46
3. is not a bug

**Comment by Zero-Bits** [comment] 2018-05-29 00:52
Fixed by #234

**Closed by Zero-Bits** 2018-05-29 00:52 UTC
